[FE][Feat] #131 : router 경로들 설정
boostcampwm-2024/web28-DDara pull request #142
Opened 2024-11-11 10:18 UTC by juwon5272

## 📝 PR 개요

- 각 페이지의 경로 설정
- 페이지에 해당하는 파일 생성

2024-11-11 10:36 UTC, effozen submitted a review, later dismissed

2024-11-11 10:36 UTC, effozen commented on frontend/src/App.tsx
> +    <Route path="/channel/:channelId/host/:guestId" element={<HostView />} />
이거 서브라우터 이용해서 host랑 guest 뺼 수 있을 것 같아 보입니다.
다만, 이대로도 충분하고 다른 개발일정도 있으니 추후 리팩토링 사항으로 넣어두면 좋을 것 같아요!

2024-11-12 01:28 UTC, happyhyep requested changes

2024-11-12 01:28 UTC, happyhyep commented on frontend/src/App.tsx
> +    <Route path="/channel/:channelId/host/:guestId" element={<HostView />} />
HostView에는 guestId가 필요없지 않을까요?? 그냥 channelId까지만 하거나 host까지만 있어도 괜찮을 것 같습니다!

2024-11-12 01:28 UTC, happyhyep commented on frontend/src/main.tsx
>  import './index.css';
index.css도 삭제해서 tailwind로 변경해야할것같아요!

2024-11-12 01:50 UTC, juwon5272 commented on frontend/src/App.tsx
> +    <Route path="/channel/:channelId/host/:guestId" element={<HostView />} />
아 각 게스트마다의 페이지를 구분하려고 guestId까지 넣었는데 수정하곘습니다

2024-11-12 02:20 UTC, effozen commented on frontend/src/main.tsx
>  import './index.css';
index.css는 놔둘수 있나요? 컴포넌트 의존성 관련해서 공통 컴포넌트에서 하위 컴포넌트에게 스타일 주입할때 사용하고자 합니다.

예: .specificButton > button {@apply w-30} 이런식으로요!

2024-11-12 02:34 UTC, juwon5272 commented on frontend/src/main.tsx
>  import './index.css';
다시 돌려놓겠습니다ㅎㅎ

2024-11-12 06:12 UTC, effozen commented
본 PR의 빠른 머지가 필요해보입니다. (통합이나 충돌의 이유)
한번 확인 가능할까요?

2024-11-12 06:14 UTC, leedongyull approved these changes

2024-11-12 06:21 UTC, happyhyep approved these changes

2024-11-12 06:27 UTC, merged