[FE][FEAT] #145 - 플로팅 버튼 구현
boostcampwm-2024/web28-DDara pull request #150
Opened 2024-11-12 08:29 UTC by leedongyull

## 📝 PR 개요

> Floating 버튼 구현
> 애니메이션 구현
> tsDoc 작성

---

## ✅ 체크리스트 (Checklist)

> - [x] 우측 하단에 버튼이 존재
> - [x] 토글이 가능해야하며 메뉴가 위쪽으로 펼쳐져야 함.
> - [x] 메뉴를 통해 타입을 선택할 수 있음.
> - [x] 타입 선택 시 토글이 닫히고 아이콘의 모양이 변경돼야함.

---

## 🔄 관련 이슈 (Linked Issues)

> #145  해결

---

## 📷 스크린샷 및 동영상 (선택 사항)

![Vite-React-TS-외-페이지-2개-개인-Microsoft_-Edge-2024-11-12-17-16-05](https://github.com/user-attachments/assets/3a217246-bc00-4e51-91fe-c9dc24d39377)

---
## 참고사항

- 컴포넌트를 만들기는 했습니다만, 들어가야 할 것들이 많고 애니메이션도 있어 공통 컴포넌트가 맞는지가 의문이 듭니다!
- 또한, 확장성도 저작도구의 종류가 늘어나는 정도는 type 선언을 통해 고려했습니다만 공통 컴포넌트로 사용하기 위해서는 더 분리를 해야할 것 같습니다!
- 따라서 이 컴포넌트를 종속 시킬 것 인지 공통 컴포넌트로 마이그레이션 해야할 지 궁금합니다!
- 이외에도 잘못된 부분들 알려주시면 감사하겠습니다!!

2024-11-12 08:44 UTC, effozen requested changes

2024-11-12 08:44 UTC, effozen commented on frontend/src/component/common/FloatingButton/FloatingButton.tsx
> + * FloatingButton 컴포넌트는 도구 선택 및 메뉴 토글 기능을 제공하는 플로팅 버튼을 렌더링합니다.
TSDoc 양식은 @param @return @remarks @example 순서로 적어주시면 됩니다. 주석으로 코드가 길어지기에, 일관된 흐름으로 (특히 보통 자주 쓰이는 패턴으로) 가져가야 좀 더 읽기 쉽다는 장점이 있어서 참고해주시면 될 것 같습니다!

2024-11-12 08:44 UTC, effozen commented on frontend/src/component/common/FloatingButton/FloatingButton.tsx
> +export const FloatingButton: React.FC = () => {
리액트 함수에 대한 타입으로 React.FC를 사용하시는 이유가 있을까요?
순수하게 궁금해서 여쭙습니다.

2024-11-12 08:44 UTC, effozen commented on frontend/src/component/common/FloatingButton/FloatingButton.tsx
> +  const [toolType, setToolType] = useState<ButtonType>(ButtonType.CLOSE);
타입을 Enum으로 빼는 거 좋네요. 저도 참고하겠습니다.

2024-11-12 08:44 UTC, effozen commented on frontend/src/component/common/FloatingButton/FloatingButton.tsx
> + * FloatingButton 컴포넌트는 도구 선택 및 메뉴 토글 기능을 제공하는 플로팅 버튼을 렌더링합니다.
관련해서는 네이버 지도 주석을 참고해주시면 좋을 것 같아요.
GPT나 AI에게 맡길때는 저 주석 긁어서 이 양식대로 작성해줘 하면 해줄거에요.

그게 아니라 Copilot 사용한다면, TSDoc이나, JSDoc 인식시 자동으로 처리해줍니다.

마지막으로, AI아니더라도 플러그인 쓰시면 쉽게 처리되실거에요!

2024-11-12 08:44 UTC, effozen commented on frontend/src/component/common/FloatingButton/FloatingButton.tsx
> +                  'w-[78px]',
수치를 고정된 px값으로 둔 이유가 있으실까요? Tailwind에 유사한 값이 있으면 그걸 사용해도 좋을 것 같아요. 반응형 대응을 위해서 아마 테일윈드 측에서 rem으로 설정해뒀을거에요!

2024-11-12 08:44 UTC, effozen commented on frontend/src/component/common/FloatingButton/enumTypes.ts
> +/**
Enum에 대해서 전부 상세하게 적혀있는게 좋네요!
개인적으로는 변경이 적지만 공통으로 사용하는 타입이나 Enum에는 주석이 있으면 좋다라는 주의라서,
실제로 가독성이 정말 좋아져서 좋은 거 같아요! 고생하셨습니다.

2024-11-12 08:47 UTC, happyhyep requested changes
comment 남겨주신 부분은 전체적인 플로우를 확인해야 답변할 수 있을 것 같아서, 백엔드 구현 하고나서 보면 너무 늦어질 것 같아 저는 코드만 보고 수정하면 좋을 것 같은 부분 남겨뒀습니다! 

코멘트 달아주신 내용은 재도님과 주원님께서 확인해보시고 결정하시는 게 더 빠르고 좋을 것 같습니다!

그리고 영상 캡처해주신 것만 확인하고 코드로는 확인하지 않아서 정확하지는 않은데, 디자인이 많이 반영되지 않은 것 같습니다! 토글 간의 간격도 조금 달라 보이고. 토글 간에 그림자도 넣어뒀었는데 그런 디테일이 반영되지 않은 것 같습니다! 확인 부탁드립니닷!

2024-11-12 08:47 UTC, happyhyep commented on frontend/src/component/common/FloatingButton/enumTypes.ts
> +];
type과 enum은 파일이 분리되면 좋을 것 같습니다! 저같은 경우에는 보통 `frontend/src/types/enum.ts` `frontend/src/types/types.ts`와 같은 식으로 분리하는데, 이렇게 컴포넌트/페이지 별로 enum과 type 파일을 만드시는 거라면, 'frontend/src/component/common/types/enum.ts` 'frontend/src/component/common/types/type.ts`와 같은 식으로만 분리해주는 건 어떨까 싶습니다!

2024-11-12 08:47 UTC, happyhyep commented on frontend/src/component/common/FloatingButton/FloatingButton.tsx
> +    setIsMenuOpen(false);
제가 잠깐 코드를 보기에는 `ButtonType.OPEN`과 `isMenuOpen이 true인 상태`가 동일한 것으로 보이는데, 다른 점이 있는지 궁금합니다!

만약 이유가 있어서 분리하신 거라면, ButtonType에는 (사실 ButtonType이라는 이름보다는 ToolType이 더 좋아보입니다)   START_MARKER = 'START_MARKER', // 출발지 설정 버튼, DESTINATION_MARKER = 'DESTINATION_MARKER', // 도착지 설정 버튼, LINE_DRAWING = 'LINE_DRAWING', // 경로 그리기 버튼 

이렇게 세개만 있는 것이 더 좋을 것 같습니다!

그리고 저 메뉴 토글이 열려있는지 여부는 따로 관리하는 편이 좋을 것 같습니다!

2024-11-12 08:47 UTC, happyhyep commented on frontend/src/component/common/FloatingButton/FloatingButton.tsx
> +          style={{ bottom: isMenuOpen ? `${(index + 1) * 60}px` : '0px' }}
이런 곳에서도 만약 ButtonType.OPEN과 isMenuOpen이 동일한 거라면,,, 변경해도 좋을 것 같아보입니다!

2024-11-12 08:47 UTC, happyhyep commented on frontend/src/component/common/FloatingButton/enumTypes.ts
> +export enum ButtonType {
위에서 언급한 것처럼 ButtonType이라는 이름보다는 조금 더 구체적으로 명시되면 좋겟습니다! 예를들면 ToolType이라던가, ToolStatus라던가 등...

2024-11-12 08:47 UTC, happyhyep commented on frontend/src/component/common/FloatingButton/FloatingButton.tsx
> +export const FloatingButton: React.FC = () => {
제가 아직 프론트 코드를 구체적으로 살펴보지는 못해서, 혹시 재도님께서 React.FC와 같은 타입 지양하자고 남겨주셨던 걸로 기억하는데 이 부분 통일된건지 궁금합니다!

2024-11-12 08:48 UTC, leedongyull commented on frontend/src/component/common/FloatingButton/FloatingButton.tsx
> +export const FloatingButton: React.FC = () => {
아이고 이게 tsDoc 작성한다고 AI에게 맡겼더니 자기 멋대로.. 바로 수정했습니다!

2024-11-12 08:48 UTC, effozen commented
공통컴포넌트 이슈 관련해서는 크게 신경쓰지 않아도 될 것 같아요.  FlatingButton에는 추가적인 요소만 들어갈 수 있도록 확장성만 고려해서, 도메인 종속적으로 만들어도 될 것 같아요.

만약 공통컴포넌트로 만든다고 하면, 제 방식으로는 의존성(데이터 등을)외부에서 전부 주입한다고 생각하고 작업하셔도 좋을 것 같아요.
다만, 이렇게 되면 버튼 하나하나 당 이벤트를 어떻게 처리할지에 대한 의문이 생기게 되는데, 이는 이벤트 위임으로 한번에 처리하는 방법도 있긴 합니다.

Dropdown을 기준으로 말하면, 드랍다운도 하나하나 다 Router를 걸어줘야하는데, 저는 이에 대해서는 `Dropdown wrapper` 측에서 공통 이벤트를 하나 받아서, 그걸 기준으로 처리하게 할 생각입니다.

데이터도 외부에서 넘겨주는 만큼 이벤트도 외부에서 하나만 넘겨주면 결과적으로 Dropdown은 배열 하나와 이벤트 하나 이렇게 받으면 되는 형태가 나올 것 같아서요.

다만 이게 좋은 방법인지는 고민좀 해보려고 합니다.

2024-11-12 08:48 UTC, leedongyull commented on frontend/src/component/common/FloatingButton/FloatingButton.tsx
> + * FloatingButton 컴포넌트는 도구 선택 및 메뉴 토글 기능을 제공하는 플로팅 버튼을 렌더링합니다.
아하 감사합니다!! 확인했습니다!

2024-11-12 08:48 UTC, leedongyull commented on frontend/src/component/common/FloatingButton/enumTypes.ts
> +/**
감사합니다!!

2024-11-12 08:49 UTC, leedongyull commented on frontend/src/component/common/FloatingButton/FloatingButton.tsx
> +                  'w-[78px]',
확인했습니다! 수정하겠습니다!

2024-11-12 08:59 UTC, leedongyull commented on frontend/src/component/common/FloatingButton/enumTypes.ts
> +];
확인했습니다! 수정하겠습니다

2024-11-12 09:24 UTC, leedongyull commented on frontend/src/component/common/FloatingButton/FloatingButton.tsx
> +    setIsMenuOpen(false);
지금 확인해본 결과 우선  ButtonType에 OPEN과 CLOSE 가 있는 이유는 아이콘 + 현재 저작도구가 선택되지 않았다를 표현하고자 하였습니다!

isMenuOpen을 사용하지 않고 ButtonType으로 할 시 다 괜찮은데 저작도구가 선택된 상태에서 다시 버튼을 눌렀을 때, 펼쳐지지 않고  CLOSE 로 변경된 다음에 다시 눌러야 펼쳐지는 상황이 생겼습니다.. 

이때문에 저도 고민을 조금 하다가 ToolCategory를 만들어 관리했는데, 이를 어떻게 수정하면 좋을 지 모르겠습니다..

2024-11-12 09:26 UTC, leedongyull commented on frontend/src/component/common/FloatingButton/enumTypes.ts
> +export enum ButtonType {
ButtonType은 버튼이 가질 수 있는 모든 상태에 대한 것이라고 생각하여 사용했고, 저작도구 관련해서는 ToolCategory를 만들어 관리했었는데 수정이 필요한지 궁금합니다!!

2024-11-12 11:37 UTC, happyhyep commented on frontend/src/component/common/FloatingButton/FloatingButton.tsx
> +    setIsMenuOpen(false);
음... 아직 코드를 구체적으로 본 게 아니라서 잘 모르겠긴 한데, 만약 그렇다면 차라리 타입을 NONE과 같은걸 추가하시는 건 어떠신가요? 지금 상태에서 OPEN CLOSE만 없애고, NONE을 추가하면, 아무것도 선택되지 않은 상태 (토글이 닫혀있든 열려있든)를 NONE으로 둘 수 있을 거고, 나머지 세개 툴에 대한 타입은 그대로 두고요!
그리고 하신 것ㄹ처럼 isOpened같은 변수로 상태 관리만 하면 좋을 것 같습니다!
결론적으로 토글이 열려았는지 닫혀있는지는 위에 설정한 변수로 관리하고, 현재 선택되어 있는 상태는 enum으로 관리하는 거죠!
횡설수설이긴한데, 지금 OPEN CLOSE 있는것보다는 없는게 더 나을 것 같습니다!

2024-11-12 11:39 UTC, happyhyep commented on frontend/src/component/common/FloatingButton/enumTypes.ts
> +export enum ButtonType {
음 그냥 제가 처음 봤을 때 ButtonType에는ㄴ 정말 공통적인게 들어갈 거라고 생각했어요! 예를들면 버튼타입에 add, delete, 아니면 이전으로 가는 Back버튼 이런 느낌으로..? 정말 공통으로 버튼이 사용될 때 사용될 것 같은 이름이라, 꼭 tool이 아니더라도, toggle이라던가 등등 좀 더 이름을 구체화하는 건 필요할 것 같습니다!

2024-11-12 11:40 UTC, happyhyep submitted a review, later dismissed

2024-11-12 12:15 UTC, juwon5272 submitted a review, later dismissed

2024-11-12 12:34 UTC, leedongyull commented on frontend/src/component/common/FloatingButton/FloatingButton.tsx
> +      className={classNames('absolute', 'bottom-5', 'right-10', 'flex', 'flex-col', 'items-center')}
아 맞습니다 사실 큰 이유는 없고 보기 좋아서 + 하다 보니 아무 생각 없이..ㅎㅎ

2024-11-12 13:44 UTC, effozen approved these changes

2024-11-13 11:00 UTC, leedongyull commented on frontend/src/component/common/FloatingButton/enumTypes.ts
> +export enum ButtonType {
우선 ButtonState로 구체화 했습니당... 우선 구현이 급한 것 같아 어느정도 구현하고 리팩토링하면서 다시 고쳐볼게요!!

2024-11-13 11:04 UTC, effozen approved these changes

2024-11-13 12:42 UTC, juwon5272 approved these changes

2024-11-13 14:31 UTC, happyhyep approved these changes

2024-11-13 22:05 UTC, merged